In [ ]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Input dataset (4 samples with 3 features)
inputs = np.array([[0, 0, 1],
                   [1, 1, 1],
                   [1, 0, 1],
                   [0, 1, 1]])

# Output dataset (4 samples with 1 output)
outputs = np.array([[0], [1], [1], [0]])

# Seed the random number generator
np.random.seed(1)


In [ ]:
# Initialize weights randomly with mean 0
input_layer_neurons = inputs.shape[1]
hidden_layer_neurons = 4
output_layer_neurons = 1

# Weight matrices
weights_input_hidden = 2 * np.random.random((input_layer_neurons, hidden_layer_neurons)) - 1
weights_hidden_output = 2 * np.random.random((hidden_layer_neurons, output_layer_neurons)) - 1


In [ ]:
# Training the neural network
for epoch in range(10000):
    # Forward propagation
    input_layer = inputs
    hidden_layer_input = np.dot(input_layer, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output_layer_output = sigmoid(output_layer_input)

    # Backpropagation
    output_layer_adjustments = error * sigmoid_derivative(output_layer_output)
    hidden_layer_error = output_layer_adjustments.dot(weights_hidden_output.T)
    hidden_layer_adjustments = hidden_layer_error * sigmoid_derivative(hidden_layer_output)

    # Update weights
    weights_hidden_output += hidden_layer_output.T.dot(output_layer_adjustments)
    weights_input_hidden += input_layer.T.dot(hidden_layer_adjustments)



In [ ]:
print("Trained weights after 10000 epochs:")
print("Weights between input and hidden layer:")
print(weights_input_hidden)
print("Weights between hidden and output layer:")
print(weights_hidden_output)

print("Predicted outputs after training:")
print(output_layer_output)

Trained weights after 10000 epochs:
Weights between input and hidden layer:
[[-2.59036615  4.42368034 -4.67337507  0.26599911]
 [-0.34937658 -0.44301149  0.03901232 -0.21076069]
 [ 0.79068639 -1.52027476  1.90298497  0.46136533]]
Weights between hidden and output layer:
[[-2.89966893]
 [ 6.37273701]
 [-6.05605498]
 [ 0.66423352]]
Predicted outputs after training:
[[0.00328786]
 [0.99636765]
 [0.99673376]
 [0.00272381]]
